joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: slambot_controller/cmd_vel  # Updated topic name
      deadman_buttons: [5]
      axis_mappings:
        twist-linear-x:
          axis: 1
          scale: 30.0
          offset: 0.0
        twist-angular-z:
          axis: 3
          scale: 20.0
          offset: 0.0
